using UnityEngine;

public class FloatingArrow : MonoBehaviour
{
    public float amplitude = 0.5f;
    public float frequency = 1f;

    [SerializeField]
    private float rotationSpeed = 50f;

    private Vector3 startPosition;

    void Start()
    {
        startPosition = transform.position;
    }

    void Update()
    {
        // Movimiento vertical con funci贸n seno para la flotaci贸n
        float newY = startPosition.y + Mathf.Sin(Time.time * frequency) * amplitude;

        // Movimiento de rotaci贸n usando deltaTime para suavidad
        float rotationAmount = rotationSpeed * Time.deltaTime;

        // Aplicamos el movimiento en el eje Y manteniendo los otros ejes en la posici贸n original
        transform.position = new Vector3(startPosition.x, newY, startPosition.z);

        transform.Rotate(-Vector3.forward, rotationAmount, Space.Self);
    }
}
